response_count = 67

[[choices]]
key = "steel"
label = "Steel"
top_choice_share = 0.12529
mean_rating = 4.447761
median_rating = 4.0
std_rating = 3.408028

[[choices]]
key = "aluminium"
label = "Aluminium"
top_choice_share = 0.080514
mean_rating = 4.820896
median_rating = 5.0
std_rating = 3.357151

[[choices]]
key = "titanium"
label = "Titanium"
top_choice_share = 0.157629
mean_rating = 4.955224
median_rating = 5.0
std_rating = 3.59053

[[choices]]
key = "glass"
label = "Glass"
top_choice_share = 0.096186
mean_rating = 4.507463
median_rating = 5.0
std_rating = 3.12067

[[choices]]
key = "wood"
label = "Wood"
top_choice_share = 0.1733
mean_rating = 5.119403
median_rating = 5.0
std_rating = 3.254472

[[choices]]
key = "thermoplastic"
label = "Thermoplastic"
top_choice_share = 0.121559
mean_rating = 4.223881
median_rating = 5.0
std_rating = 3.137365

[[choices]]
key = "elastomer"
label = "Elastomer"
top_choice_share = 0.016584
mean_rating = 3.746269
median_rating = 4.0
std_rating = 2.787109

[[choices]]
key = "thermoset"
label = "Thermoset"
top_choice_share = 0.073798
mean_rating = 5.253731
median_rating = 6.0
std_rating = 2.872773

[[choices]]
key = "composite"
label = "Composite"
top_choice_share = 0.155141
mean_rating = 5.835821
median_rating = 6.0
std_rating = 2.700152
