"""Generate the checked-in problem catalog docs from the packaged registry."""

from __future__ import annotations

import argparse
import json
import re
import sys
from collections import Counter
from collections.abc import Mapping, Sequence
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[1]
OUTPUT_ROOT = ROOT / "docs" / "problem_catalog"
AUTO_COMMENT = ".. Auto-generated by scripts/generate_problem_catalog_docs.py. Do not edit by hand."
FAMILY_TITLES = {
    "text": "Text Problem Catalog",
    "decision": "Decision Problem Catalog",
    "optimization": "Optimization Problem Catalog",
    "grammar": "Grammar Problem Catalog",
}
FAMILY_DESCRIPTIONS = {
    "text": "This page lists all packaged text problems and ideation prompts.",
    "decision": "This page lists all packaged decision problems and their candidate-space summaries.",
    "optimization": "This page lists all packaged optimization benchmarks and their variable counts.",
    "grammar": "This page lists all packaged grammar problems and their initial transition structure.",
}
STATEMENT_HEADING_CHARS = ("~", "^", '"', "'", "+", "*")
INLINE_CODE_RE = re.compile(r"(?<!`)`([^`]+)`(?!`)")
MARKDOWN_HEADING_RE = re.compile(r"^(#{1,6})\s+(.+?)\s*$")
MARKDOWN_LINK_RE = re.compile(r"(?<!`)!\[[^\]]*\]\([^)]+\)|(?<!`)\[[^\]]+\]\([^)]+\)")

sys.path.insert(0, str(ROOT / "src"))

from design_research_problems import ProblemRegistry  # noqa: E402
from design_research_problems.problems import (  # noqa: E402
    DecisionProblem,
    GrammarProblem,
    OptimizationProblem,
    Problem,
    ProblemKind,
    TextProblem,
)


def _heading(title: str, adornment: str) -> str:
    """Return one reStructuredText heading block.

    Args:
        title: Heading title text.
        adornment: Repeated underline character.

    Returns:
        Rendered heading block ending with a newline.
    """
    return f"{title}\n{adornment * len(title)}\n"


def _normalize_inline_code(text: str) -> str:
    """Convert Markdown inline-code spans to reStructuredText literals.

    Args:
        text: Source text that may include single-backtick spans.

    Returns:
        Text with Markdown inline code rewritten as double-backtick literals.
    """
    normalized = " ".join(text.split())
    return INLINE_CODE_RE.sub(r"``\1``", normalized)


def _render_bullets(items: Sequence[str]) -> list[str]:
    """Render one bullet list.

    Args:
        items: Bullet item strings to render.

    Returns:
        Rendered bullet-list lines.
    """
    if not items:
        return ["- none", ""]
    lines = [f"- {_normalize_inline_code(item)}" for item in items]
    lines.append("")
    return lines


def _render_code_block(language: str, text: str) -> list[str]:
    """Render a literal code block directive.

    Args:
        language: Pygments lexer or plain-text label.
        text: Literal block contents.

    Returns:
        Rendered directive lines.
    """
    block_lines = [f".. code-block:: {language}", ""]
    if text.strip():
        block_lines.extend(f"   {line}" if line else "" for line in text.strip().splitlines())
    else:
        block_lines.append("   ")
    block_lines.append("")
    return block_lines


def _render_definition_list(items: Sequence[tuple[str, str]]) -> list[str]:
    """Render one reStructuredText definition list.

    Args:
        items: Ordered `(term, value)` pairs.

    Returns:
        Rendered definition-list lines.
    """
    lines: list[str] = []
    for term, value in items:
        lines.append(term)
        lines.append(f"   {value}")
    lines.append("")
    return lines


def _render_list_table(
    headers: Sequence[str],
    rows: Sequence[Sequence[str]],
    widths: Sequence[int] | None = None,
) -> list[str]:
    """Render one list-table directive.

    Args:
        headers: Column headers in display order.
        rows: Table rows with one string per column.
        widths: Optional explicit Sphinx widths.

    Returns:
        Rendered list-table lines.
    """
    lines = [".. list-table::", "   :header-rows: 1"]
    if widths:
        lines.append("   :widths: " + " ".join(str(width) for width in widths))
    lines.append("")
    header_cells = [_normalize_inline_code(cell).replace("|", r"\|") for cell in headers]
    lines.append(f"   * - {header_cells[0]}")
    for cell in header_cells[1:]:
        lines.append(f"     - {cell}")
    for row in rows:
        cells = [_normalize_inline_code(" ".join(str(cell).split())).replace("|", r"\|") for cell in row]
        lines.append(f"   * - {cells[0]}")
        for cell in cells[1:]:
            lines.append(f"     - {cell}")
    lines.append("")
    return lines


def _format_number(value: Any) -> str:
    """Return one compact numeric string.

    Args:
        value: Numeric object to format.

    Returns:
        Compact decimal text or the default string conversion.
    """
    if isinstance(value, bool):
        return "yes" if value else "no"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        if value.is_integer():
            return str(int(value))
        return f"{value:.6g}"
    return str(value)


def _json_ready(value: object) -> object:
    """Convert one nested parameter payload into JSON-serializable data.

    Args:
        value: Raw manifest parameter value.

    Returns:
        JSON-serializable data with deterministic nested mappings.
    """
    if isinstance(value, Mapping):
        return {str(key): _json_ready(item) for key, item in sorted(value.items(), key=lambda item: str(item[0]))}
    if isinstance(value, (list, tuple)):
        return [_json_ready(item) for item in value]
    return value


def _serialize_parameter_value(value: object) -> str:
    """Render one manifest parameter as compact deterministic text.

    Args:
        value: Raw manifest parameter value.

    Returns:
        Single-line JSON-style text for the parameter.
    """
    if isinstance(value, str):
        return _normalize_inline_code(value)
    if isinstance(value, (bool, int, float)):
        return _format_number(value)
    return json.dumps(_json_ready(value), ensure_ascii=True, separators=(", ", ": "), sort_keys=True)


def _normalize_statement_markdown(markdown: str, title: str) -> list[str]:
    """Convert the supported statement Markdown subset to reStructuredText.

    Args:
        markdown: Raw packaged Markdown statement.
        title: Page title used to suppress a duplicated leading H1.

    Returns:
        Rendered reStructuredText lines, including a blank line terminator.
    """
    source_lines = markdown.strip().splitlines()
    while source_lines and not source_lines[0].strip():
        source_lines.pop(0)
    if source_lines:
        match = MARKDOWN_HEADING_RE.match(source_lines[0].strip())
        if match and len(match.group(1)) == 1 and match.group(2).strip() == title.strip():
            source_lines.pop(0)
            while source_lines and not source_lines[0].strip():
                source_lines.pop(0)

    for line in source_lines:
        stripped = line.strip()
        if not stripped:
            continue
        if MARKDOWN_LINK_RE.search(stripped):
            return _render_code_block("markdown", markdown)
        if stripped.startswith(">") or stripped.startswith("!"):
            return _render_code_block("markdown", markdown)
        if re.match(r"^\d+\.\s+", stripped):
            return _render_code_block("markdown", markdown)
        if re.match(r"^[|].+[|]$", stripped):
            return _render_code_block("markdown", markdown)
        if re.match(r"^<[^>]+>$", stripped):
            return _render_code_block("markdown", markdown)

    lines: list[str] = []
    index = 0
    while index < len(source_lines):
        raw_line = source_lines[index]
        stripped = raw_line.strip()
        if not stripped:
            if lines and lines[-1] != "":
                lines.append("")
            index += 1
            continue

        if stripped.startswith("```"):
            language = stripped[3:].strip() or "text"
            block: list[str] = []
            index += 1
            while index < len(source_lines) and not source_lines[index].strip().startswith("```"):
                block.append(source_lines[index])
                index += 1
            if index >= len(source_lines):
                return _render_code_block("markdown", markdown)
            lines.extend(_render_code_block(language, "\n".join(block)))
            index += 1
            continue

        heading_match = MARKDOWN_HEADING_RE.match(stripped)
        if heading_match:
            level = min(len(heading_match.group(1)), len(STATEMENT_HEADING_CHARS))
            heading = _normalize_inline_code(heading_match.group(2).strip())
            adornment = STATEMENT_HEADING_CHARS[level - 1]
            lines.extend([heading, adornment * len(heading), ""])
            index += 1
            continue

        if re.match(r"^[-*]\s+", stripped):
            while index < len(source_lines):
                bullet_line = source_lines[index].strip()
                if not bullet_line:
                    break
                bullet_match = re.match(r"^[-*]\s+(.*)$", bullet_line)
                if bullet_match is None:
                    break
                lines.append(f"- {_normalize_inline_code(bullet_match.group(1))}")
                index += 1
            lines.append("")
            continue

        paragraph: list[str] = []
        while index < len(source_lines):
            paragraph_line = source_lines[index].strip()
            if not paragraph_line:
                break
            if paragraph_line.startswith("```") or MARKDOWN_HEADING_RE.match(paragraph_line):
                break
            if re.match(r"^[-*]\s+", paragraph_line):
                break
            paragraph.append(paragraph_line)
            index += 1
        if paragraph:
            lines.append(_normalize_inline_code(" ".join(paragraph)))
            lines.append("")
            continue

        return _render_code_block("markdown", markdown)

    while lines and not lines[-1]:
        lines.pop()
    lines.append("")
    return lines


def _render_common_sections(metadata: Any, problem: Problem) -> list[str]:
    """Render the common sections shared by every generated problem page.

    Args:
        metadata: Problem metadata object from the registry.
        problem: Instantiated problem object.

    Returns:
        Common section lines through the rendered statement.
    """
    implementation = f"``{metadata.implementation}``" if metadata.implementation else f"``{type(problem).__name__}``"
    quick_facts_rows = [
        ("Problem ID", f"``{metadata.problem_id}``"),
        ("Problem Family", metadata.kind.value),
        ("Implementation", implementation),
        (
            "Capabilities",
            ", ".join(f"``{flag}``" for flag in metadata.capabilities) if metadata.capabilities else "none",
        ),
        (
            "Study Suitability",
            ", ".join(f"``{flag}``" for flag in metadata.study_suitability) if metadata.study_suitability else "none",
        ),
        ("Tags", ", ".join(f"``{tag}``" for tag in metadata.taxonomy.tags) if metadata.taxonomy.tags else "none"),
    ]
    taxonomy = metadata.taxonomy
    taxonomy_items = [
        ("Formulation", _normalize_inline_code(taxonomy.formulation)) if taxonomy.formulation else None,
        ("Convexity", _normalize_inline_code(taxonomy.convexity)) if taxonomy.convexity else None,
        (
            "Design Variable Type",
            _normalize_inline_code(taxonomy.design_variable_type),
        )
        if taxonomy.design_variable_type
        else None,
        ("Is Dynamic", "yes" if taxonomy.is_dynamic else "no"),
        ("Orientation", _normalize_inline_code(taxonomy.orientation)) if taxonomy.orientation else None,
        (
            "Feasibility Ratio Hint",
            _format_number(taxonomy.feasibility_ratio_hint),
        )
        if taxonomy.feasibility_ratio_hint is not None
        else None,
        ("Objective Mode", _normalize_inline_code(taxonomy.objective_mode)) if taxonomy.objective_mode else None,
        (
            "Constraint Nature",
            _normalize_inline_code(taxonomy.constraint_nature),
        )
        if taxonomy.constraint_nature
        else None,
        ("Bounds Summary", _normalize_inline_code(taxonomy.bounds_summary)) if taxonomy.bounds_summary else None,
        (
            "Tags",
            ", ".join(f"``{tag}``" for tag in taxonomy.tags) if taxonomy.tags else "none",
        ),
        ("Deliverable Type", _normalize_inline_code(taxonomy.deliverable_type)) if taxonomy.deliverable_type else None,
        (
            "Timebox Hint (Minutes)",
            str(taxonomy.timebox_hint_minutes),
        )
        if taxonomy.timebox_hint_minutes is not None
        else None,
        ("Participants", _normalize_inline_code(taxonomy.participants)) if taxonomy.participants else None,
        (
            "Evaluation Mode",
            _normalize_inline_code(taxonomy.evaluation_mode),
        )
        if taxonomy.evaluation_mode
        else None,
    ]
    lines = [
        _heading("Quick Facts", "-").rstrip(),
        "",
        *_render_list_table(("Field", "Value"), quick_facts_rows, widths=(20, 80)),
        _heading("Taxonomy", "-").rstrip(),
        "",
        *_render_definition_list([item for item in taxonomy_items if item is not None]),
        _heading("Statement", "-").rstrip(),
        "",
        *_normalize_statement_markdown(problem.statement_markdown, metadata.title),
    ]
    return lines


def _render_detail_page(metadata: Any, manifest: Any, problem: Problem) -> str:
    """Render one generated problem-detail page.

    Args:
        metadata: Registry metadata for the problem.
        manifest: Loaded manifest for the problem.
        problem: Instantiated problem object.

    Returns:
        Full reStructuredText content for the detail page.
    """
    lines = [
        AUTO_COMMENT,
        "",
        _heading(metadata.title, "=").rstrip(),
        "",
        _normalize_inline_code(metadata.summary),
        "",
        f"See :doc:`../{metadata.kind.value}` for the {metadata.kind.value} family index.",
        "",
        *_render_common_sections(metadata, problem),
    ]

    if isinstance(problem, TextProblem):
        lines.extend(
            [
                _heading("Prompt Profile", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Field", "Value"),
                    (
                        ("Deliverable Type", metadata.taxonomy.deliverable_type or "n/a"),
                        (
                            "Timebox Hint (Minutes)",
                            str(metadata.taxonomy.timebox_hint_minutes)
                            if metadata.taxonomy.timebox_hint_minutes is not None
                            else "n/a",
                        ),
                        ("Participants", metadata.taxonomy.participants or "n/a"),
                        ("Evaluation Mode", metadata.taxonomy.evaluation_mode or "n/a"),
                    ),
                    widths=(25, 75),
                ),
            ]
        )

    if isinstance(problem, DecisionProblem):
        context_rows = []
        for key, label in (
            ("decision_maker", "Decision Maker"),
            ("market_segment", "Market Segment"),
            ("decision_scope", "Decision Scope"),
        ):
            value = problem.parameters.get(key)
            if isinstance(value, str) and value.strip():
                context_rows.append((label, value))
        if context_rows:
            lines.extend(
                [
                    _heading("Decision Context", "-").rstrip(),
                    "",
                    *_render_list_table(("Field", "Value"), context_rows, widths=(25, 75)),
                ]
            )

        if problem.decision_variables or problem.decision_variable_specs:
            lines.extend([_heading("Decision Variables", "-").rstrip(), ""])
            if problem.decision_variables:
                lines.extend(_render_bullets(problem.decision_variables))
            if problem.decision_variable_specs:
                rows = [
                    (
                        spec.symbol,
                        spec.label,
                        spec.unit or "n/a",
                        _format_number(spec.lower_bound),
                        _format_number(spec.upper_bound),
                    )
                    for spec in problem.decision_variable_specs
                ]
                lines.extend(
                    _render_list_table(
                        ("Symbol", "Label", "Unit", "Lower Bound", "Upper Bound"),
                        rows,
                        widths=(10, 30, 15, 20, 20),
                    )
                )

        if problem.objectives or problem.objective_specs:
            lines.extend([_heading("Objectives", "-").rstrip(), ""])
            if problem.objectives:
                lines.extend(_render_bullets(problem.objectives))
            if problem.objective_specs:
                rows = [
                    (
                        spec.key,
                        spec.label,
                        spec.sense,
                        spec.domain,
                        "yes" if spec.executable else "no",
                        ", ".join(f"``{name}``" for name in spec.variables) if spec.variables else "none",
                        spec.expression,
                    )
                    for spec in problem.objective_specs
                ]
                lines.extend(
                    _render_list_table(
                        ("Key", "Label", "Sense", "Domain", "Executable", "Variables", "Expression"),
                        rows,
                        widths=(10, 22, 10, 13, 10, 15, 20),
                    )
                )

        if problem.constraints or problem.constraint_specs:
            lines.extend([_heading("Constraints", "-").rstrip(), ""])
            if problem.constraints:
                lines.extend(_render_bullets(problem.constraints))
            if problem.constraint_specs:
                rows = [
                    (
                        spec.key,
                        spec.label,
                        spec.relation,
                        spec.domain,
                        "yes" if spec.executable else "no",
                        ", ".join(f"``{name}``" for name in spec.variables) if spec.variables else "none",
                        spec.expression,
                    )
                    for spec in problem.constraint_specs
                ]
                lines.extend(
                    _render_list_table(
                        ("Key", "Label", "Relation", "Domain", "Executable", "Variables", "Expression"),
                        rows,
                        widths=(10, 22, 10, 13, 10, 15, 20),
                    )
                )

        if problem.assumptions:
            lines.extend([_heading("Assumptions", "-").rstrip(), ""])
            lines.extend(_render_bullets(problem.assumptions))

        lines.extend([_heading("Candidate Space", "-").rstrip(), ""])
        summary_rows = [
            ("Candidate Kind", problem.candidate_kind),
            ("Candidate Count", str(problem.candidate_count)),
        ]
        if problem.candidate_kind == "discrete-option":
            summary_rows.extend(
                [
                    ("Competitor Profile Count", str(len(problem.competitor_profiles))),
                    ("Total Option Count", str(problem.option_count)),
                ]
            )
        else:
            summary_rows.append(("Default Choice Metric", problem.default_choice_metric))
            response_count = getattr(problem, "_response_count", 0)
            if response_count:
                summary_rows.append(("Response Count", str(response_count)))
        lines.extend(_render_list_table(("Field", "Value"), summary_rows, widths=(25, 75)))

        if problem.candidate_kind == "discrete-option":
            rows = [
                (
                    factor.key,
                    factor.label,
                    factor.unit or "n/a",
                    ", ".join(_format_number(level) for level in factor.levels),
                    ", ".join(_format_number(value) for value in factor.part_worths) if factor.part_worths else "n/a",
                )
                for factor in problem.option_factors
            ]
            lines.extend(
                [
                    _heading("Option Factors", "~").rstrip(),
                    "",
                    *_render_list_table(
                        ("Key", "Label", "Unit", "Levels", "Part Worths"),
                        rows,
                        widths=(10, 20, 12, 33, 25),
                    ),
                ]
            )
        else:
            rows = [
                (
                    benchmark.key,
                    benchmark.label,
                    _format_number(benchmark.top_choice_share),
                    _format_number(benchmark.mean_rating),
                    _format_number(benchmark.median_rating),
                    _format_number(benchmark.std_rating),
                )
                for benchmark in problem.choice_benchmarks
            ]
            lines.extend(
                [
                    _heading("Empirical Benchmarks", "~").rstrip(),
                    "",
                    *_render_list_table(
                        ("Key", "Label", "Top Choice Share", "Mean Rating", "Median Rating", "Std Rating"),
                        rows,
                        widths=(14, 30, 14, 14, 14, 14),
                    ),
                ]
            )

    if isinstance(problem, OptimizationProblem):
        eq_constraints = sum(1 for constraint in problem.constraints if constraint.kind == "eq")
        ineq_constraints = sum(1 for constraint in problem.constraints if constraint.kind == "ineq")
        lines.extend(
            [
                _heading("Problem Shape", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Field", "Value"),
                    (
                        ("Design Variable Count", str(len(problem.bounds.lb))),
                        ("Bound Summary", metadata.taxonomy.bounds_summary or "n/a"),
                        ("Total Constraint Count", str(len(problem.constraints))),
                        ("Equality Constraint Count", str(eq_constraints)),
                        ("Inequality Constraint Count", str(ineq_constraints)),
                    ),
                    widths=(30, 70),
                ),
                _heading("Variable Bounds", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Variable", "Lower Bound", "Upper Bound"),
                    [
                        (f"``x[{index}]``", _format_number(lower), _format_number(upper))
                        for index, (lower, upper) in enumerate(
                            zip(problem.bounds.lb.tolist(), problem.bounds.ub.tolist(), strict=True)
                        )
                    ],
                    widths=(25, 37, 38),
                ),
                _heading("Manifest Parameters", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Key", "Value"),
                    [
                        (str(key), _serialize_parameter_value(value))
                        for key, value in sorted(manifest.parameters.items(), key=lambda item: str(item[0]))
                    ]
                    or [("none", "none")],
                    widths=(25, 75),
                ),
                _heading("Library Interface", "-").rstrip(),
                "",
                *_render_bullets(
                    (
                        "``generate_initial_solution(seed=None)``",
                        "``objective(x)``",
                        "``evaluate(x)``",
                        "``solve(initial_solution=None, seed=None, maxiter=200)``",
                    )
                ),
            ]
        )

    if isinstance(problem, GrammarProblem):
        initial_state = problem.initial_state()
        transitions = problem.enumerate_transitions(initial_state)
        grouped = Counter(transition.rule_name for transition in transitions)
        lines.extend(
            [
                _heading("Problem Shape", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Field", "Value"),
                    (
                        ("State Type", type(initial_state).__name__),
                        ("Initial Transition Count", str(len(transitions))),
                        (
                            "Initial Rule Names",
                            ", ".join(f"``{name}``" for name in sorted(grouped)) if grouped else "none",
                        ),
                    ),
                    widths=(25, 75),
                ),
                _heading("Manifest Parameters", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Key", "Value"),
                    [
                        (str(key), _serialize_parameter_value(value))
                        for key, value in sorted(manifest.parameters.items(), key=lambda item: str(item[0]))
                    ]
                    or [("none", "none")],
                    widths=(25, 75),
                ),
                _heading("Initial Transition Summary", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Rule Name", "Transition Count"),
                    [(name, str(count)) for name, count in sorted(grouped.items())] or [("none", "0")],
                    widths=(70, 30),
                ),
                _heading("Library Interface", "-").rstrip(),
                "",
                *_render_bullets(
                    (
                        "``initial_state()``",
                        "``enumerate_transitions(state)``",
                        "``enumerate_next_states(state)``",
                        "``evaluate(state)``",
                    )
                ),
            ]
        )

    if metadata.citations:
        lines.extend([_heading("Sources", "-").rstrip(), ""])
        citation_rows = [(f"``{citation.key}``", citation.summary_text()) for citation in metadata.citations]
        lines.extend(_render_list_table(("Key", "Summary"), citation_rows, widths=(20, 80)))
        lines.extend([_heading("Raw Citation Records", "-").rstrip(), ""])
        for citation in metadata.citations:
            language = "bibtex" if citation.kind == "bibtex" else "text"
            lines.extend(_render_code_block(language, citation.raw_text))

    if metadata.assets:
        lines.extend(
            [
                _heading("Assets", "-").rstrip(),
                "",
                *_render_list_table(
                    ("Name", "Media Type", "Description", "Resource Path"),
                    [
                        (
                            asset.name,
                            asset.media_type,
                            asset.description or "n/a",
                            f"``{asset.resource_path}``",
                        )
                        for asset in metadata.assets
                    ],
                    widths=(15, 20, 35, 30),
                ),
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def _build_catalog_data() -> tuple[dict[str, list[dict[str, object]]], int]:
    """Collect the registry-backed context used by all generated pages.

    Returns:
        A mapping of problem-kind strings to ordered entry dictionaries and the
        total number of problems in the catalog.
    """
    registry = ProblemRegistry()
    manifests = registry._catalog()
    grouped: dict[str, list[dict[str, object]]] = {kind.value: [] for kind in ProblemKind}
    total = 0
    for metadata in registry.list():
        manifest = manifests[metadata.problem_id]
        problem = registry.get(metadata.problem_id)
        detail_path = OUTPUT_ROOT / metadata.kind.value / f"{metadata.problem_id}.rst"
        grouped[metadata.kind.value].append(
            {
                "metadata": metadata,
                "manifest": manifest,
                "problem": problem,
                "detail_path": detail_path,
                "detail_doc": f"{metadata.kind.value}/{metadata.problem_id}",
            }
        )
        total += 1
    return grouped, total


def _render_family_page(kind: str, entries: Sequence[dict[str, object]]) -> str:
    """Render one generated family-index page.

    Args:
        kind: Problem-kind string such as `text` or `decision`.
        entries: Ordered entry dictionaries for the family.

    Returns:
        Full reStructuredText content for the family page.
    """
    title = FAMILY_TITLES[kind]
    lines = [
        AUTO_COMMENT,
        "",
        _heading(title, "=").rstrip(),
        "",
        f"{FAMILY_DESCRIPTIONS[kind]} There are currently {len(entries)} packaged {kind} problems.",
        "",
        f"For the conceptual overview, see :doc:`../problems/{kind}`.",
        "",
        ".. toctree::",
        "   :maxdepth: 1",
        "",
    ]
    lines.extend(f"   {entry['detail_doc']}" for entry in entries)
    return "\n".join(lines).rstrip() + "\n"


def _render_catalog_index(grouped: Mapping[str, Sequence[dict[str, object]]], total: int) -> str:
    """Render the top-level problem-catalog landing page.

    Args:
        grouped: Family-to-entry mapping.
        total: Total problem count.

    Returns:
        Full reStructuredText content for the landing page.
    """
    lines = [
        AUTO_COMMENT,
        "",
        _heading("Problem Catalog", "=").rstrip(),
        "",
        "This is the complete generated catalog of packaged design research problems.",
        "",
        "Current counts:",
        "",
        f"- Text: {len(grouped['text'])}",
        f"- Decision: {len(grouped['decision'])}",
        f"- Optimization: {len(grouped['optimization'])}",
        f"- Grammar: {len(grouped['grammar'])}",
        f"- Total: {total}",
        "",
        ".. toctree::",
        "   :maxdepth: 1",
        "",
        "   text",
        "   decision",
        "   optimization",
        "   grammar",
        "",
        "For the conceptual problem-family overview, see :doc:`../problems/index`.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _render_all_files() -> dict[Path, str]:
    """Render the full generated docs tree in memory.

    Returns:
        Mapping of absolute output paths to rendered file contents.
    """
    grouped, total = _build_catalog_data()
    rendered: dict[Path, str] = {
        OUTPUT_ROOT / "index.rst": _render_catalog_index(grouped, total),
    }
    for kind in ("text", "decision", "optimization", "grammar"):
        entries = grouped[kind]
        rendered[OUTPUT_ROOT / f"{kind}.rst"] = _render_family_page(kind, entries)
        for entry in entries:
            rendered[entry["detail_path"]] = _render_detail_page(
                entry["metadata"],
                entry["manifest"],
                entry["problem"],
            )
    return rendered


def _write_or_check(rendered: Mapping[Path, str], check: bool) -> None:
    """Write the rendered docs tree or verify it is current.

    Args:
        rendered: Expected generated files and contents.
        check: Whether to validate instead of writing.

    Raises:
        SystemExit: If check mode detects drift.
    """
    existing = set(OUTPUT_ROOT.rglob("*.rst")) if OUTPUT_ROOT.exists() else set()
    expected = set(rendered)

    if check:
        if existing != expected:
            raise SystemExit("docs/problem_catalog is out of date.")
        for path, content in rendered.items():
            current = path.read_text(encoding="utf-8")
            if current != content:
                raise SystemExit("docs/problem_catalog is out of date.")
        return

    OUTPUT_ROOT.mkdir(parents=True, exist_ok=True)
    for path in existing - expected:
        path.unlink()
    for path in expected:
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(rendered[path], encoding="utf-8")


def main() -> None:
    """Write or validate the generated problem catalog docs.

    Raises:
        SystemExit: If ``--check`` is used and the generated docs are stale.
    """
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()

    rendered = _render_all_files()
    _write_or_check(rendered, check=args.check)


if __name__ == "__main__":
    main()
