"""Scalarized MoneyMaker Hip Pump optimization problem."""

from __future__ import annotations

import math
from dataclasses import dataclass
from typing import cast

import numpy
from numpy.typing import NDArray

from design_research_problems._catalog._manifest import ProblemManifest
from design_research_problems.problems._metadata import ProblemMetadata
from design_research_problems.problems._optimization import (
    Bounds,
    ConstraintDefinition,
    OptimizationProblem,
    OptimizationResult,
)

_HDPE_VOLUME_COST = 3808.0
_UNION_COST = 0.75
_CYLINDER_COST = 1.96
_SMALL_WASHER_COST = 0.31
_LARGE_WASHER_COST = 0.45
_HANDLE_ROD_COST = 1.57
_SPLASH_CUP_COST = 0.74
_INLET_PLATE_COST = 0.88
_OUTLET_PLATE_COST = 1.09
_TOP_PLATE_COST = 1.09
_NIPPLE_COST = 1.05
_OUTLET_PIPE_COST = 1.13
_INLET_PIPE_COST = 1.07

_REF_X1 = 0.017
_REF_X3 = 0.045
_REF_X4 = 0.05
_REF_X5 = 0.632
_REF_X8 = 0.687
_REF_X9 = 0.019

_P_DOWN = 27.7
_P_UP = 33.7
_D_SHOULDER = 1.3
_D_KNEE = 0.5
_T_CYCLE = 3.0
_GRAVITY = 9.8
_HAZEN_WILLIAMS = 140.0
_WATER_DENSITY = 1000.0
_DEFAULT_WELL_DEPTH = 7.0
_DEFAULT_HORIZONTAL_RUN = 18.0
_VAPOR_PRESSURE = 101_300.0
_MECHANICAL_EFFICIENCY = 0.9
_VOLUMETRIC_EFFICIENCY = 0.99

_OUTER_DIAMETER_SLOPE = 1.094
_OUTER_DIAMETER_OFFSET = 0.0028

_CURRENT_TALL_TANK_VECTOR = numpy.array(
    [0.0210, 0.0450, 0.6320, 3.0000, 0.6870, 0.0190, 136.2, 123.7, 0.1831, 0.2449],
    dtype=float,
)
_SAME_FLOW_MIN_COST_TALL_TANK_VECTOR = numpy.array(
    [0.0170, 0.0404, 0.5015, 18.0000, 0.5015, 0.0148, 62.5, 129.6, 0.3986, 0.2210],
    dtype=float,
)
_MAX_FLOW_SAME_COST_TALL_TANK_VECTOR = numpy.array(
    [0.0188, 0.0410, 0.5792, 18.0000, 0.5792, 0.0213, 45.0, 125.5, 0.5538, 0.2413],
    dtype=float,
)
_PUBLISHED_TALL_TANK_BASELINES = (
    ("published_current_tall_tank", _CURRENT_TALL_TANK_VECTOR),
    ("published_same_flow_min_cost_tall_tank", _SAME_FLOW_MIN_COST_TALL_TANK_VECTOR),
    ("published_max_flow_same_cost_tall_tank", _MAX_FLOW_SAME_COST_TALL_TANK_VECTOR),
)
_REDUCED_SOLVER_INDICES = (0, 1, 2, 3, 4, 5, 8)
_REDUCED_SOLVER_DERIVED_INDICES = (6, 7, 9)


def _outer_diameter(inner_diameter: float) -> float:
    """Return the hose or cylinder outer diameter from the paper's linear fit.

    Args:
        inner_diameter: Hose or cylinder inner diameter in meters.

    Returns:
        Corresponding outer diameter in meters.
    """
    return _OUTER_DIAMETER_SLOPE * inner_diameter + _OUTER_DIAMETER_OFFSET


def _head_loss_major(length: float, velocity: float, diameter: float) -> float:
    """Return the Hazen-Williams major head loss in meters.

    Args:
        length: Pipe run length in meters.
        velocity: Mean fluid velocity in meters per second.
        diameter: Hydraulic diameter in meters.

    Returns:
        Major head-loss term in meters of water.
    """
    volumetric_flow = 0.25 * math.pi * diameter**2 * velocity
    numerator = 10.67 * length * volumetric_flow**1.85
    denominator = (_HAZEN_WILLIAMS**1.85) * diameter**4.87
    return float(numerator / denominator)


def _pump_head(force: float, diameter: float) -> float:
    """Return the hydraulic head generated by the piston force.

    Args:
        force: Applied piston force in newtons.
        diameter: Cylinder inner diameter in meters.

    Returns:
        Generated hydraulic head in meters.
    """
    piston_area = 0.25 * math.pi * diameter**2
    return force / (_WATER_DENSITY * _GRAVITY * piston_area)


@dataclass(frozen=True)
class MoneyMakerHipPumpDesign:
    """Expanded design variables reconstructed from the reduced vector."""

    x1: float
    """Inlet pipe inner diameter in meters."""
    x2: float
    """Inlet pipe outer diameter in meters."""
    x3: float
    """Cylinder inner diameter in meters."""
    x4: float
    """Cylinder outer diameter in meters."""
    x5: float
    """Pump stroke length in meters."""
    x6: float
    """Inlet horizontal run length in meters."""
    x7: float
    """Well depth in meters."""
    x8: float
    """Handle or rod length in meters."""
    x9: float
    """Outlet pipe inner diameter in meters."""
    x10: float
    """Outlet pipe outer diameter in meters."""
    x11: float
    """Outlet horizontal run length in meters."""
    x12: float
    """Outlet vertical rise to the storage tank in meters."""
    x13: float
    """Downstroke piston force in newtons."""
    x14: float
    """Upstroke piston force in newtons."""
    x15: float
    """Downstroke water velocity in meters per second."""
    x16: float
    """Upstroke water velocity in meters per second."""


class MoneyMakerHipPumpProblem(OptimizationProblem):
    """Scalarized cost-minimization subproblem derived from McComb et al."""

    def __init__(
        self,
        metadata: ProblemMetadata,
        statement_markdown: str = "",
        target_flow_rate_lps: float = 0.18,
        target_tank_height_m: float = 3.0,
        well_depth_m: float = _DEFAULT_WELL_DEPTH,
        horizontal_run_m: float = _DEFAULT_HORIZONTAL_RUN,
    ) -> None:
        """Initialize the packaged tall-tank cost minimization instance.

        Args:
            metadata: Shared packaged metadata.
            statement_markdown: Human-readable problem statement.
            target_flow_rate_lps: Fixed target flow rate in liters per second.
            target_tank_height_m: Fixed delivery head in meters.
            well_depth_m: Fixed well depth in meters.
            horizontal_run_m: Fixed horizontal distance between well and tank.
        """
        super().__init__(metadata=metadata, statement_markdown=statement_markdown)
        self.target_flow_rate_lps = target_flow_rate_lps
        self.target_flow_rate_m3_per_s = target_flow_rate_lps / 1000.0
        self.target_tank_height_m = target_tank_height_m
        self.well_depth_m = well_depth_m
        self.horizontal_run_m = horizontal_run_m
        self.bounds = Bounds(
            lb=numpy.array([0.014, 0.038, 0.5, 0.0, 0.5, 0.014, 40.0, 110.0, 0.15, 0.2], dtype=float),
            ub=numpy.array([0.028, 0.05, 0.7, 18.0, 0.75, 0.024, 150.0, 140.0, 0.6, 0.3], dtype=float),
        )
        self.constraints = [
            ConstraintDefinition(kind="eq", evaluate=self._upstroke_balance),
            ConstraintDefinition(kind="eq", evaluate=self._downstroke_balance),
            ConstraintDefinition(
                kind="eq",
                evaluate=self.flow_rate_m3_per_s,
                target=self.target_flow_rate_m3_per_s,
            ),
            ConstraintDefinition(kind="ineq", evaluate=self._downstroke_power_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._upstroke_power_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._stroke_reach_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._knee_clearance_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._cycle_time_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._piston_length_margin),
            ConstraintDefinition(kind="ineq", evaluate=self._cavitation_margin),
        ]

    @classmethod
    def from_manifest(cls, manifest: ProblemManifest, statement_markdown: str) -> MoneyMakerHipPumpProblem:
        """Construct an instance from packaged manifest data.

        Args:
            manifest: Parsed packaged manifest.
            statement_markdown: Human-readable problem statement.

        Returns:
            Initialized problem instance.
        """
        target_flow_rate_lps = float(cast(float, manifest.parameters.get("target_flow_rate_lps", 0.18)))
        target_tank_height_m = float(cast(float, manifest.parameters.get("target_tank_height_m", 3.0)))
        well_depth_m = float(cast(float, manifest.parameters.get("well_depth_m", _DEFAULT_WELL_DEPTH)))
        horizontal_run_m = float(cast(float, manifest.parameters.get("horizontal_run_m", _DEFAULT_HORIZONTAL_RUN)))
        return cls(
            metadata=manifest.metadata,
            statement_markdown=statement_markdown,
            target_flow_rate_lps=target_flow_rate_lps,
            target_tank_height_m=target_tank_height_m,
            well_depth_m=well_depth_m,
            horizontal_run_m=horizontal_run_m,
        )

    def decode_design(self, variables: NDArray[numpy.float64]) -> MoneyMakerHipPumpDesign:
        """Expand the reduced 10-variable vector into the published 16-variable form.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Expanded 16-variable design with derived geometry values.

        Raises:
            ValueError: If ``variables`` is not a 10-element vector.
        """
        if variables.shape != (10,):
            raise ValueError(f"Expected a 10-variable design vector, received shape {variables.shape!r}.")

        x1, x3, x5, x6, x8, x9, x13, x14, x15, x16 = (float(value) for value in variables)
        x2 = _outer_diameter(x1)
        x4 = _outer_diameter(x3)
        x7 = self.well_depth_m
        x10 = _outer_diameter(x9)
        x11 = self.horizontal_run_m - x6
        x12 = self.target_tank_height_m
        return MoneyMakerHipPumpDesign(
            x1=x1,
            x2=x2,
            x3=x3,
            x4=x4,
            x5=x5,
            x6=x6,
            x7=x7,
            x8=x8,
            x9=x9,
            x10=x10,
            x11=x11,
            x12=x12,
            x13=x13,
            x14=x14,
            x15=x15,
            x16=x16,
        )

    def generate_initial_solution(self, seed: int | None = None) -> NDArray[numpy.float64]:
        """Return the published tall-tank low-cost design, or a seeded perturbation.

        Args:
            seed: Optional random seed for the perturbation.

        Returns:
            Initial 10-variable solution vector.
        """
        if seed is None:
            return _SAME_FLOW_MIN_COST_TALL_TANK_VECTOR.copy()

        rng = numpy.random.default_rng(seed)
        span = self.bounds.ub - self.bounds.lb
        perturbation = rng.normal(loc=0.0, scale=0.05, size=10) * span
        guess = _SAME_FLOW_MIN_COST_TALL_TANK_VECTOR + perturbation
        return numpy.clip(guess, self.bounds.lb, self.bounds.ub)

    def flow_rate_m3_per_s(self, variables: NDArray[numpy.float64]) -> float:
        """Return the average water flow rate in cubic meters per second.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Average flow rate in cubic meters per second.
        """
        design = self.decode_design(variables)
        stroke_volume = 0.25 * math.pi * design.x3**2 * design.x5
        cycle_time = design.x5 / design.x15 + design.x5 / design.x16
        return _VOLUMETRIC_EFFICIENCY * stroke_volume / cycle_time

    def flow_rate_lps(self, variables: NDArray[numpy.float64]) -> float:
        """Return the average water flow rate in liters per second.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Average flow rate in liters per second.
        """
        return 1000.0 * self.flow_rate_m3_per_s(variables)

    def cost_usd(self, variables: NDArray[numpy.float64]) -> float:
        """Return the projected manufacturing cost from the 2018 paper.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Estimated unit cost in U.S. dollars.
        """
        design = self.decode_design(variables)
        ch_in = _HDPE_VOLUME_COST * 0.25 * math.pi * (design.x6 + design.x7) * (design.x2**2 - design.x1**2)
        ch_out = _HDPE_VOLUME_COST * 0.25 * math.pi * (design.x11 + design.x12) * (design.x10**2 - design.x9**2)
        ccyl = _UNION_COST * (design.x4 / _REF_X4) + _CYLINDER_COST * (
            (design.x4 - design.x3) / (_REF_X4 - _REF_X3)
        ) * (design.x5 / _REF_X5)
        cpist = (
            _SMALL_WASHER_COST * ((design.x3 - 0.006) / (_REF_X3 - 0.006)) ** 2
            + _LARGE_WASHER_COST * (design.x3 / _REF_X3) ** 2
            + _HANDLE_ROD_COST * (design.x8 / _REF_X8)
            + _SPLASH_CUP_COST * (design.x4 / _REF_X4)
        )
        cbody = (
            _INLET_PLATE_COST * (design.x1 / _REF_X1) ** 2
            + _OUTLET_PLATE_COST * (design.x9 / _REF_X9) ** 2
            + _TOP_PLATE_COST * (design.x3 / _REF_X3) ** 2
            + _NIPPLE_COST * (design.x3 / _REF_X3)
            + _OUTLET_PIPE_COST * (design.x9 / _REF_X9)
            + _INLET_PIPE_COST * (design.x1 / _REF_X1)
        )
        return ch_in + ch_out + ccyl + cpist + cbody

    def objective_components(self, variables: NDArray[numpy.float64]) -> dict[str, float]:
        """Return the main reported objective values for one design vector.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Mapping of named scalar outputs reported for the design.
        """
        return {
            "flow_rate_lps": self.flow_rate_lps(variables),
            "tank_height_m": self.target_tank_height_m,
            "cost_usd": self.cost_usd(variables),
        }

    def objective(self, variables: NDArray[numpy.float64]) -> float:
        """Return the scalar cost objective.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Cost objective value in U.S. dollars.
        """
        return self.cost_usd(variables)

    def solve(
        self,
        initial_solution: NDArray[numpy.float64] | None = None,
        seed: int | None = None,
        maxiter: int = 200,
    ) -> OptimizationResult:
        """Solve the reduced MoneyMaker subproblem with SciPy's SLSQP baseline.

        The three equality constraints can be satisfied analytically once the
        inlet diameter, cylinder diameter, stroke length, inlet run, handle
        length, outlet diameter, and downstroke velocity are chosen. This
        solver therefore searches over those seven free variables and
        reconstructs the remaining quantities at every candidate point.

        Args:
            initial_solution: Optional full 10-variable starting point.
            seed: Optional random seed used to generate deterministic restart
                candidates.
            maxiter: Maximum SLSQP iterations per restart.

        Returns:
            Locally optimized feasible pump design.

        Raises:
            ValueError: If ``initial_solution`` is provided with the wrong
                shape.
        """
        from scipy.optimize import minimize

        restarts = self._solver_start_points(initial_solution=initial_solution, seed=seed)
        reduced_lb = self.bounds.lb[list(_REDUCED_SOLVER_INDICES)]
        reduced_ub = self.bounds.ub[list(_REDUCED_SOLVER_INDICES)]
        slsqp_bounds = list(zip(reduced_lb.tolist(), reduced_ub.tolist(), strict=True))
        best_vector: NDArray[numpy.float64] | None = None
        best_score = math.inf
        total_nit = 0
        total_nfev = 0

        for start in restarts:
            if self._reconstruct_solution(start) is None:
                continue
            raw_result = minimize(
                self._solver_objective,
                x0=start,
                method="SLSQP",
                bounds=slsqp_bounds,
                constraints=(
                    {"type": "eq", "fun": self._solver_equality_residuals},
                    {"type": "ineq", "fun": self._solver_inequality_margins},
                ),
                options={"maxiter": maxiter, "ftol": 1e-9, "disp": False},
            )
            total_nit += int(getattr(raw_result, "nit", 0) or 0)
            total_nfev += int(getattr(raw_result, "nfev", 0) or 0)
            reduced_solution = numpy.clip(
                numpy.array(raw_result.x, dtype=float, copy=True),
                reduced_lb,
                reduced_ub,
            )
            candidate = self._reconstruct_solution(reduced_solution)
            if candidate is None:
                continue
            violation = self.max_constraint_violation(candidate)
            cost = self.objective(candidate)
            score = cost + 1e6 * violation**2 + 1e3 * violation
            if score < best_score:
                best_score = score
                best_vector = candidate

        if best_vector is None:
            fallback = self.generate_initial_solution(seed=seed)
            best_vector = fallback

        max_violation = self.max_constraint_violation(best_vector)
        cost = self.objective(best_vector)
        if max_violation <= 1e-6:
            message = f"Converged SciPy SLSQP baseline (cost {cost:.2f} USD, max violation {max_violation:.3g})."
        else:
            message = (
                f"SciPy SLSQP returned a best-effort design (cost {cost:.2f} USD, max violation {max_violation:.3g})."
            )
        return OptimizationResult(
            x=numpy.array(best_vector, dtype=float, copy=True),
            fun=cost,
            success=max_violation <= 1e-6,
            message=message,
            nit=total_nit,
            nfev=total_nfev,
        )

    def _solver_objective(self, reduced_variables: NDArray[numpy.float64]) -> float:
        """Return the reduced SLSQP objective value.

        Args:
            reduced_variables: Seven free design variables.

        Returns:
            Cost objective for the reconstructed design, or a large penalty for
            invalid reconstructions.
        """
        candidate = self._reconstruct_solution(reduced_variables)
        if candidate is None:
            return 1e12
        return self.objective(candidate)

    def _solver_equality_residuals(self, reduced_variables: NDArray[numpy.float64]) -> NDArray[numpy.float64]:
        """Return equality residuals for the reduced SLSQP model.

        Args:
            reduced_variables: Seven free design variables.

        Returns:
            Vector of equality residuals.
        """
        candidate = self._reconstruct_solution(reduced_variables)
        if candidate is None:
            count = sum(constraint.kind == "eq" for constraint in self.constraints)
            return numpy.ones(count, dtype=float)
        residuals = [
            float(constraint.evaluate(candidate) - constraint.target)
            for constraint in self.constraints
            if constraint.kind == "eq"
        ]
        return numpy.array(residuals, dtype=float)

    def _solver_inequality_margins(self, reduced_variables: NDArray[numpy.float64]) -> NDArray[numpy.float64]:
        """Return inequality margins for the reduced SLSQP model.

        Args:
            reduced_variables: Seven free design variables.

        Returns:
            Vector of inequality margins, each of which must remain nonnegative.
        """
        candidate = self._reconstruct_solution(reduced_variables)
        if candidate is None:
            count = sum(constraint.kind == "ineq" for constraint in self.constraints) + 2 * len(
                _REDUCED_SOLVER_DERIVED_INDICES
            )
            return -numpy.ones(count, dtype=float)

        margins = [
            float(constraint.evaluate(candidate) - constraint.target)
            for constraint in self.constraints
            if constraint.kind == "ineq"
        ]
        for index in _REDUCED_SOLVER_DERIVED_INDICES:
            margins.append(float(candidate[index] - self.bounds.lb[index]))
            margins.append(float(self.bounds.ub[index] - candidate[index]))
        return numpy.array(margins, dtype=float)

    def _solver_start_points(
        self,
        initial_solution: NDArray[numpy.float64] | None,
        seed: int | None,
    ) -> tuple[NDArray[numpy.float64], ...]:
        """Return deterministic reduced-coordinate restart points.

        Args:
            initial_solution: Optional full 10-variable starting point.
            seed: Optional random seed for deterministic jittered restarts.

        Returns:
            Reduced-coordinate start vectors.

        Raises:
            ValueError: If ``initial_solution`` has the wrong shape.
        """
        starts: list[NDArray[numpy.float64]] = []
        if initial_solution is not None:
            candidate = numpy.array(initial_solution, dtype=float, copy=True)
            if candidate.shape != (10,):
                raise ValueError(f"Expected a 10-variable design vector, received shape {candidate.shape!r}.")
            starts.append(candidate[list(_REDUCED_SOLVER_INDICES)])
        else:
            starts.append(self.generate_initial_solution(seed=seed)[list(_REDUCED_SOLVER_INDICES)])
        for _, vector in _PUBLISHED_TALL_TANK_BASELINES:
            starts.append(vector[list(_REDUCED_SOLVER_INDICES)].copy())

        reduced_lb = self.bounds.lb[list(_REDUCED_SOLVER_INDICES)]
        reduced_ub = self.bounds.ub[list(_REDUCED_SOLVER_INDICES)]
        midpoint = 0.5 * (reduced_lb + reduced_ub)
        starts.append(midpoint)

        rng = numpy.random.default_rng(0 if seed is None else seed)
        span = reduced_ub - reduced_lb
        for _ in range(6):
            starts.append(reduced_lb + rng.random(reduced_lb.shape) * span)

        return tuple(starts)

    def _reconstruct_solution(self, reduced_variables: NDArray[numpy.float64]) -> NDArray[numpy.float64] | None:
        """Rebuild a full 10-variable vector while satisfying all equalities.

        Args:
            reduced_variables: Seven free design variables used by the solver.

        Returns:
            Full 10-variable design vector, or ``None`` when reconstruction is
            not physically valid.
        """
        x1, x3, x5, x6, x8, x9, x15 = (float(value) for value in reduced_variables)
        area_term = _VOLUMETRIC_EFFICIENCY * 0.25 * math.pi * x3**2
        denominator = area_term / self.target_flow_rate_m3_per_s - 1.0 / x15
        if denominator <= 0.0:
            return None

        x16 = 1.0 / denominator
        if x16 <= 0.0:
            return None

        area = 0.25 * math.pi * x3**2
        upstroke_term = (
            _head_loss_major(x6 + self.well_depth_m, x16, x1)
            + _head_loss_major(0.5 * x5, x16, _VOLUMETRIC_EFFICIENCY * x3)
            + self.well_depth_m
            + 0.5 * x5
            + x16**2 / (2.0 * _GRAVITY)
        )
        downstroke_term = (
            _head_loss_major(self.horizontal_run_m - x6 + self.target_tank_height_m, x15, x9)
            + _head_loss_major(0.5 * x5, x15, _VOLUMETRIC_EFFICIENCY * x3)
            + self.well_depth_m
            - 0.5 * x5
            - x15**2 / (2.0 * _GRAVITY)
        )
        x14 = upstroke_term * _WATER_DENSITY * _GRAVITY * area
        x13 = downstroke_term * _WATER_DENSITY * _GRAVITY * area
        return numpy.array([x1, x3, x5, x6, x8, x9, x13, x14, x15, x16], dtype=float)

    def _hard_constraint_violation(self, variables: NDArray[numpy.float64]) -> float:
        """Return the total violation across inequality constraints only.

        The published vectors in the cited papers are rounded, so the hydraulic
        balance equalities can show residuals that are not useful for comparing
        representative baselines. The baseline solver therefore scores only the
        hard inequality limits plus the explicit flow-rate mismatch.

        Args:
            variables: Candidate design vector.

        Returns:
            Total positive inequality-constraint violation.
        """
        violation = 0.0
        for constraint in self.constraints:
            if constraint.kind != "ineq":
                continue
            violation += max(constraint.target - constraint.evaluate(variables), 0.0)
        return float(violation)

    def _upstroke_balance(self, variables: NDArray[numpy.float64]) -> float:
        """Return the upstroke fluid-balance equality residual.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Upstroke equality-constraint residual in meters of head.
        """
        design = self.decode_design(variables)
        velocity_head = design.x16**2 / (2.0 * _GRAVITY)
        return (
            _head_loss_major(design.x6 + design.x7, design.x16, design.x1)
            + _head_loss_major(0.5 * design.x5, design.x16, _VOLUMETRIC_EFFICIENCY * design.x3)
            + design.x7
            + 0.5 * design.x5
            + velocity_head
            - _pump_head(design.x14, design.x3)
        )

    def _downstroke_balance(self, variables: NDArray[numpy.float64]) -> float:
        """Return the downstroke fluid-balance equality residual.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Downstroke equality-constraint residual in meters of head.
        """
        design = self.decode_design(variables)
        velocity_head = design.x15**2 / (2.0 * _GRAVITY)
        return (
            _head_loss_major(design.x11 + design.x12, design.x15, design.x9)
            + _head_loss_major(0.5 * design.x5, design.x15, _VOLUMETRIC_EFFICIENCY * design.x3)
            + design.x7
            - 0.5 * design.x5
            - velocity_head
            - _pump_head(design.x13, design.x3)
        )

    def _downstroke_power_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the remaining downstroke power budget.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Remaining downstroke mechanical power margin.
        """
        design = self.decode_design(variables)
        return _MECHANICAL_EFFICIENCY * _P_DOWN - design.x13 * design.x15

    def _upstroke_power_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the remaining upstroke power budget.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Remaining upstroke mechanical power margin.
        """
        design = self.decode_design(variables)
        return _MECHANICAL_EFFICIENCY * _P_UP - design.x14 * design.x16

    def _stroke_reach_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the remaining ergonomic shoulder reach margin.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Positive slack before exceeding the shoulder reach limit.
        """
        design = self.decode_design(variables)
        return _D_SHOULDER - (design.x5 + design.x8)

    def _knee_clearance_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the clearance above the knee-height lower bound.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Positive clearance above the minimum knee-height bound.
        """
        design = self.decode_design(variables)
        return design.x8 - _D_KNEE

    def _cycle_time_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the slack above the minimum cycle time.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Positive slack relative to the minimum cycle time.
        """
        design = self.decode_design(variables)
        return design.x5 / design.x15 + design.x5 / design.x16 - _T_CYCLE

    def _piston_length_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the piston-over-stroke margin.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Positive slack between rod length and stroke length.
        """
        design = self.decode_design(variables)
        return design.x8 - design.x5

    def _cavitation_margin(self, variables: NDArray[numpy.float64]) -> float:
        """Return the remaining cavitation pressure margin.

        Args:
            variables: Reduced 10-variable optimization vector.

        Returns:
            Pressure margin before cavitation occurs.
        """
        design = self.decode_design(variables)
        cylinder_area = 0.25 * math.pi * design.x3**2
        return _VAPOR_PRESSURE - design.x14 / cylinder_area
